baseurl = "/"
languageCode = "en-us"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
# theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "main"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.en]
    title = "SeoYul's Blog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    lastModDisplay = "Modified:"

    [languages.en.params.logo]
      logoText = "SeoYul Yoon"
      logoHomeLink = "/"
    # or
    #
    #  path = "https://avatars.githubusercontent.com/u/19742930?v=4"
    #  alt = "SeoYul Photo"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/info"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/Seo-yul"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "Linkedin"
        url = "https://www.linkedin.com/in/yoon-seoyul/"        
                
#      [[languages.en.menu.main]]
#        identifier = "posts"
#        name = "Posts"
#        url = "/posts"
